version: '2'
services:
  nginx:
   container_name: some-nginx
   image: nginx:1.13
   restart: always
   ports:
   - 80:80
   - 443:443
   volumes:
   - ./nginx/conf.d:/etc/nginx/conf.d
 
  mysql:
   container_name: some-mysql
   image: mysql/mysql-server:5.7
    :
    MYSQL_DATABASE: ecommerce
    MYSQL_USER: root
    MYSQL_ROOT_PASSWORD:
    MYSQL_PASSWORD:
   ports:
   - "3306:3306"
   restart: always
  
  app:
    restart: always
    build: ./backend
    working_dir: /backend
    volumes:
      - ./backend:/backend
      - ~/.m2:/root/.m2
    expose:
      - "8080"
    command: mvn clean spring-boot:run
    depends_on:
      - nginx
      - mysql